### ISSUE TITLE
analogRead() bug

### ISSUE THREAD

**Issue by jbuckner** [HashNuke/Python-Arduino-Prototyping-API#2]
The analogRead() function took one too many parameters and didn't send the pin number that gets read. I fixed it up:

<pre>
def analogRead(self, pin):
    self.__sendData('4')
    self.__sendPin(pin)
    return self.__getData()
</pre>

**Comment by HashNuke** [comment]
Thanks for the tip. I'll look it up and fix it.

**Comment by HashNuke** [comment]
Thank you. Fixed it and closing issue.
